[project]
name = "datapipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "curl-cffi>=0.16.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.140.13",
    "httpx>=0.28.1",
    "newspaper3k>=0.2.8",
    "pydantic>=2.13.4",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "redis>=8.1.0",
    "structlog>=26.1.0",
    "trafilatura>=2.2.0",
]
