export type source_scope = "Technical" | "Gaming" | "Cinema";


export interface Source {
    _id?: string; //  ID will be generated by the server and is used for the responces.
    source_name: string;
    source_type: string;
    nationality: string;
    source_url: string;
    source_scope: source_scope;  //locing the value that can be assigned to this particular resource...
}
